# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MChat' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MChat
  pod 'CocoaAsyncSocket'
  pod 'MBProgressHUD'
  pod 'Toast'
  target 'MChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
